on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, synchronize ]

name: PHPUnit
jobs:
  build-test:
    if: contains(github.event.pull_request.labels.*.name, 'run tests')
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - php: 8.0
            wordpress: trunk
            pro: master
            lite: master
          - php: 7.2
            wordpress: trunk
            pro: master
            lite: master

    name: ${{ matrix.pro }} with ${{ matrix.lite }} on PHP ${{ matrix.php }} and WP ${{ matrix.wordpress }}
    steps:
      - uses: actions/checkout@v3.5.3

      - uses: shivammathur/setup-php@2.25.4
        with:
          php-version: ${{ matrix.php }}
          tools: phpunit-polyfills
      - name: Installing WordPress
        run: |
          export WP_DEVELOP_DIR=/tmp/wordpress/
          git clone --depth=50 --branch="${{ matrix.wordpress }}" https://github.com/WordPress/wordpress-develop.git /tmp/wordpress
          git clone --depth=50 --branch="${{ matrix.lite }}" https://github.com/Strategy11/formidable-forms.git /tmp/wordpress/src/wp-content/plugins/formidable
          git clone --depth=50 --branch="${{ matrix.pro }}" https://${{ secrets.FRM_PRO_AUTH }}@github.com/Strategy11/formidable.git /tmp/wordpress/src/wp-content/plugins/formidable-pro
          cd ..
          cp -r "${GITHUB_REPOSITORY#*/}" "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          cd /tmp/wordpress/
          pwd
          cp wp-tests-config-sample.php wp-tests-config.php
          sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
          sed -i "s/yourusernamehere/root/" wp-tests-config.php
          sed -i "s/yourpasswordhere/root/" wp-tests-config.php
      - name: Creating database
        run: |
          sudo /etc/init.d/mysql start
          mysql -u root -proot -e "CREATE DATABASE wordpress_tests;"
      - name: PhpUnit tests
        run: |
          cd "/tmp/wordpress/src/wp-content/plugins/${GITHUB_REPOSITORY#*/}"
          pwd
          phpunit
